apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: react-redux-realworld-example-app
  description: Redux example app
  annotations:
    github.com/project-slug: 5ubstance/react-redux-realworld-example-app
spec:
  type: openapi
  lifecycle: production
  owner: team-b
  system: react-apps
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: React API
      license:
        name: MIT
    servers:
      - url: http://some.url/v1
    paths:
      /things:
        get:
          summary: List all things
        post:
          summary: Create a thing
          operationId: createThings
          tags:
            - things
          responses:
            '201':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
  /things/{thingId}:

